# Generated by Django 5.2.17 on 2026-08-29 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='programs/')),
                ('description', models.TextField()),
                ('benefits', models.TextField()),
                ('duration', models.CharField(max_length=100)),
            ],
        ),
    ]
