# Generated by Django 5.2.17 on 2026-09-12 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='facebook_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='trainer',
            name='instagram_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
